### ISSUE TITLE
pdf broken on github / searchable feature ?

### ISSUE THREAD

**Issue by Altoholic** [DutchGraa/Spot-The-Book#1]
Hi

For some reason, the pdf is empty after some pages, on the github site.
But i downloaded it, and it seem complete on my e-reader.

Also, as my english is not very good, i'm used to click and search words in pdf (to look for them in embedded dictionary, on the e-reader, or wordreference.com, on my computer). But in that one, for some reason, i can't (i also can't on github). Is this something that can be fixed ?

Thank you for the reading, anyway, Alice and Spike seem to be cool folks ^^

**Comment by DutchGraa** [comment]
No that's not something for me to fix sorry.
